### PR TITLE
solved Github friend's add friend with new url

### LINKED ISSUE #75: Github Friend addition, deletion, and friend list integration with the new MongoDB URL
Github Friend addition, deletion, and friend list integration with the new MongoDB URL

## Description
The friend's table has been migrated to the no-SQL database, and so some changes with the url have been done. Features like add friend, delete friend, and get friend list are not working because of this.

## Expected Behavior
When clicked, the friend's username should be added

## Actual Behavior
Error pops up
## Possible Fix
Changing the URL in the front end and changing the serializer would work. You can see commit 162 for help

### PR DESCRIPTION
**Pull request by ronisarkarexe**
## Purpose ✨
Issue
close #75
Solved and friend list integration with the new MongoDB URL.

## Details 📝
- Change new Api URL, github add, github drop, github friends list.

## Dependencies 🔗

None

## Future Improvements 🔭
Leetcode ranking UI Enhancement

## Mentions 👀
@krishnan05

## Developer's checklist 📃
- [x ] Followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html).
- [x] Properly commented the code.
- [x] No print statements in the code. 
- [x] All the functionalities are working properly.
- [x] Changes made are not breaking any other part of the project.
- [x] No UI/UX issues are present.
- [ ] Relevant screenshots are added in the PR.
- [x] Followed the PR guidelines

### CODE REVIEW

**Comment by ronisarkarexe** [comment]
> > ## Purpose ✨
> > Issue close #75 Solved and friend list integration with the new MongoDB URL.
> > ## Details 📝
> > 
> > * Change new Api URL, github add, github drop, github friends list.
> > 
> > ## Dependencies 🔗
> > None
> > ## Future Improvements 🔭
> > Leetcode ranking UI Enhancement
> > ## Mentions 👀
> > @krishnan05
> > ## Screenshots of relevant screens 📸
> > ## Developer's checklist 📃
> > 
> > * [x ] Followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html).
> > * [x]   Properly commented the code.
> > * [x]   No print statements in the code.
> > * [x]   All the functionalities are working properly.
> > * [x]   Changes made are not breaking any other part of the project.
> > * [x]   No UI/UX issues are present.
> > * [x ]   Relevant screenshots are added in the PR.
> > * [x]   Followed the PR guidelines
> 
> Can you share relevant screenshot for this

succeddfullydone

**Comment by ronisarkarexe** [comment]
> > > ## Purpose ✨
> > > Issue close #75 Solved and friend list integration with the new MongoDB URL.
> > > ## Details 📝
> > > 
> > > * Change new Api URL, github add, github drop, github friends list.
> > > 
> > > ## Dependencies 🔗
> > > None
> > > ## Future Improvements 🔭
> > > Leetcode ranking UI Enhancement
> > > ## Mentions 👀
> > > @krishnan05
> > > ## Screenshots of relevant screens 📸
> > > ## Developer's checklist 📃
> > > 
> > > * [x ] Followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html).
> > > * [x]    Properly commented the code.
> > > * [x]    No print statements in the code.
> > > * [x]    All the functionalities are working properly.
> > > * [x]    Changes made are not breaking any other part of the project.
> > > * [x]    No UI/UX issues are present.
> > > * [x ]   Relevant screenshots are added in the PR.
> > > * [x]    Followed the PR guidelines
> > 
> > 
> > Can you share relevant screenshot for this
> 
> succeddfullydone

addf

**Comment by ronisarkarexe** [comment]
@krishnan05 how can I solve conflict?

**Comment by krishnan05** [comment]
> @krishnan05 how can I solve conflict?

I have resolved the conflicts.

**Comment by ronisarkarexe** [comment]
> > @krishnan05 how can I solve conflict?
> 
> I have resolved the conflicts.

Thanks

**Pull request merged**
