### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ananyaiitbhilai**
## Purpose ✨

Corrected the spelling of the word regularly in README.
## Details 📝

It is a non-coding task so the developer's checklist is left unchecked.

## Dependencies 🔗

None
## Future Improvements 🔭

None
## Mentions 👀

@KShivendu @Gopal-Dahale 
## Screenshots of relevant screens 📸

None

## Developer's checklist 📃
- [ ] Are the [coding guidelines](https://google.github.io/styleguide/jsguide.html) followed?
- [ ] Is the code properly commented?
- [ ] Are there any print statements in the code? 
- [ ] Are all the functionalities working properly?
- [ ] Are the changes made breaking any other part of the project?
- [ ] Are there any UI/UX issues present?
- [ ] Are relevant screenshots added in the PR?

### CODE REVIEW

**Comment by Gopal-Dahale** [comment]
Follow the [PR Format Guidelines](https://github.com/OpenLake/Leaderboard-Pro/wiki/PR-Format-Guidelines) and [pull request template](https://github.com/OpenLake/Leaderboard-Pro/blob/main/.github/pull_request_template.md).

**Comment by yatendra1999** [comment]
@Ananyaiitbhilai

**Comment by Ananyaiitbhilai** [comment]
> Follow the [PR Format Guidelines](https://github.com/OpenLake/Leaderboard-Pro/wiki/PR-Format-Guidelines) and [pull request template](https://github.com/OpenLake/Leaderboard-Pro/blob/main/.github/pull_request_template.md)

I followed that template only....pls create a sample PR so that i can follow up.

**Comment by yatendra1999** [comment]
LGTM

**Comment by Ananyaiitbhilai** [comment]
> LGTM

LGTM too

**Comment by Gopal-Dahale** [comment]
Ok, I am merging it.

**Pull request merged**
